### ISSUE TITLE
"is" attribute has capital case when extending native elements and creating in javascript.

### ISSUE THREAD

**Issue by MikeVaz** [WebReflection/document-register-element#107]
In Chrome

`class MyParagraph extends HTMLParagraphElement {};
customElements.define('my-paragraph',MyParagraph,{extends: 'p'});
var elem = new MyParagraph();
document.body.appendChild(elem);
console.log(elem.getAttribute('is'));`

The above code outputs "MY-PARAGRAPH" when using a polyfill. 
https://jsfiddle.net/webrealizer/cnhxbnhL/

It is seems minor but might break logic if you trying to use selectors like [is="my-paragraph"]

**Comment by RangerMauve** [comment]
Is it not capital when using the native browser APIs?

**Comment by WebReflection** [comment]
I have no idea how to version this ... I've never used constructors to create native subclassed elements but I've double checked in Chrome and it's lower case + I agree people would expect it to be lower-case because nobody shouts while writing HTML (beside the HTML acronym itself).

I'll give a minor a try, hopefully this is not a breaking change 'cause I am sure others would've noticed already.

**Comment by WebReflection** [comment]
`1.5.0` it is

**Comment by MikeVaz** [comment]
@RangerMauve: I think extending native elements and creating via constructor might break in Chrome without a polyfill. 

Uncaught TypeError: Illegal constructor: autonomous custom elements must extend HTMLElement

It could be a bug or a blocker specifically made by browsers to disallow using constructors for that. You can always use document.createElement instead.

**Comment by WebReflection** [comment]
@MikeVaz don't fall in that trap, if you define a `customElements` through native API extending anything that is not `HTMLElement` your class and its methods will be completely ignored and your component will never be graceful enhanced.

You need this polyfill with **every browser** to extend native components with or without the usage of constructors.

Reason being they're still mumbling about this part of the specification my polyfill provided since V0.

Mandatory Warning: use `is=""` at your own risk, Safari is **very** against its implementation and Chrome is not moving to any direction (but it keeps supporting V0 which allows `is=""`)

**Comment by MikeVaz** [comment]
According to Google you should be able to extend native elements via constructor or via document.createElement 
https://developers.google.com/web/fundamentals/getting-started/primers/customelements

But their examples breaks in Chrome right.  ¯\_(ツ)_/¯

@WebReflection I remember reading debates about "is" attribute. Could you share a link?

**Comment by WebReflection** [comment]
it ended up with people insulting each other ... good luck with this thread:
https://github.com/w3c/webcomponents/issues/509
