### ISSUE TITLE
Drop support for V0 and V1 custom builtins

### ISSUE THREAD

**Issue by dredzone** [WebReflection/document-register-element#118]
Just wondering if there are any plans to drop V0 and V1 custom builtins support and polyfill only V1 custom elements spec?

**Comment by prushforth** [comment]
I hope not before we get a chance to use it.

**Comment by WebReflection** [comment]
what would be the benefit, @dredzone ?

**Comment by dredzone** [comment]
mostly size of the polyfill and some of the unnecessary checks will go away, performance maybe?

**Comment by WebReflection** [comment]
how big is your app? this is less than 6K, I'm curious to know how much you'd gain from the total.

![screenshot from 2017-09-29 14-52-41](https://user-images.githubusercontent.com/85749/31019043-af865b20-a52e-11e7-858d-10c79f96a1e8.png)

Performance also won't change at all because target browsers that don't support native CE will use exact same fallbacks the old V0 used.

In few words, you are asking to break backward compatibility, drop some non updated browser (Chrome), for the [most widely compatible polyfill](https://github.com/WebReflection/document-register-element#tested-on) out there, and all to gain .... maybe 2K less on the whole size of your Web page ?

This polyfill is used by AFrame, StencilJS, Google AMP, and it's been working for years.

I'm afraid changing it due some perf speculation and not real-world issues is not on top of my priorities, but if you want a CE V1 only you have already less compatible alternatives from Google.

**Comment by dredzone** [comment]
Ok thanks.
