### ISSUE TITLE
installCE(window, 'auto') installs the polyfill in Chrome.

### ISSUE THREAD

**Issue by trusktr** [WebReflection/document-register-element#124]
I'm wondering by `installCE(window, 'auto')` results in the polyfill being installed in Chrome (as it already has native v1).

My module is

```js
import installCE from 'document-register-element/pony'
installCE(window, 'auto')
```

and all other files only import this file as the source of truth.

**Comment by WebReflection** [comment]
https://github.com/WebReflection/document-register-element/issues/110

**Comment by trusktr** [comment]
@WebReflection Aaah, well, since I'm transpiling code, I suppose I need the `"force"` option anyways, otherwise ` Failed to construct 'HTMLElement': Please use the 'new' operator`?

**Comment by WebReflection** [comment]
dude ... seriously? I'm living in a loop with you :smile: 

https://github.com/WebReflection/babel-plugin-transform-builtin-classes

**Comment by trusktr** [comment]
🤣  but it doesn't work with mixins.

```js
WebComponent(HTMLElement)
WebComponent(HTMLButtonElement)
WebComponent(HTMLInputElement)
```

**Comment by WebReflection** [comment]
I could address every case **but** `SomeoneElsesCustomElement`, if it doesn't use the exact same transformer.

If that class is a concern, I won't even think about a solution 'cause I don't control third parts (and not willing to).

otherwise, I might try to improve the transpiler, but I have the feeling the last case is the one you'r emost worried about.

**Comment by trusktr** [comment]
For now, `WebComponent` is used only internally by me, on my own classes, and all transpiled in the same build.
