### ISSUE TITLE
Failed to construct 'HTMLElment'

### ISSUE THREAD

**Issue by xbl** [WebReflection/document-register-element#147]
I use document-register-element 1.8.1 is ok, but I upgrade document-register-element  after 1.8.1 ,I got a error in chrome runtime:

```
Uncaught TypeError: Failed to construct 'HTMLElement': Please use the 'new' operator, this DOM object constructor cannot be called as a function.
````
I used babel 6.x
what can I do? help me ,please!

**Comment by WebReflection** [comment]
> what can I do?

You can start reading the README of this project:
https://github.com/WebReflection/document-register-element#transpilers-vs-19

**Comment by xbl** [comment]
thank you, I know that, I don't want upgrade Babel7, too many dependencies use babel 6。

**Comment by WebReflection** [comment]
then you have few options, in suggestion order:

  1. you target ES2015 instead of ES5, dropping every IE with [super ease](https://itnext.io/a-bloatless-web-d4f811c7991b)
  2. you try [this plugin](https://github.com/WebReflection/babel-plugin-transform-builtin-classes) and see if it works
  3. you don't use the latest version of this polyfill and you're stuck with it until you update to Babel 7

**Comment by WebReflection** [comment]
Just to clarify: it's not this polyfill that is broken, it's your toolchain that breaks on native JS. I won't fix what is not broken, but you probably should for the future of your project.
