### ISSUE TITLE
Rendering

### ISSUE THREAD

**Issue by sbadya** [WebReflection/document-register-element#153]
Hello!
Is it valid to render Html element ?

this.child = document.createElement('web-component');
this.html`
            <div class="aras-accordion__header">
                <span class="${className}" onclick="${() =>
			this.toggle()}"></span>
            </div>
            <div class="aras-accordion__content"></div>
            <div class="aras-accordion__content">${this.child}</div>
		`;

**Comment by MikeVaz** [comment]
What is your context `this`? Is it some sort of an object but not a HTMLElement instance?

The problem is that you trying to use HTMLElement object as String inside a template literal. Template literals work with simple types that can be converted to a string like ```var myString = ` some text ${myVar}`;```.

Instead you should be appending it using something like 
```Javascript
var myNewElement = document.createElement('my-web-component');
myParentElement.appendChild(myNewElement);
```
or 

```Javascript
myParentElement.innerHTML('<div>...some html code here... <my-web-component></my-web-component>.... more html here ...</div>');
```

**Comment by sbadya** [comment]
I mean that when some element is created via createElement method (for example var el = document.createElement('div')), can i render as html`${el}` or should be use html `<div></div>`?!

**Comment by MikeVaz** [comment]
You can't do that. 

HTML is a declarative way to build the DOM. You final goal should be to add elements to the DOM. Basically you have two options.  Use Javascript and directly manipulate DOM or use HTML string.

To understand the problem you running into try this code in the browser's console

```Javascript
var el = document.createElement('div');
`${el}`
// you'd get something like "[object HTMLDivElement]"
```
Because your HTMLElement object can't be converted to a string. 
If you still want to use HTML to add your elements to the DOM you need to use tags representing your new element `<my-web-component></my-web-component>`

**Comment by WebReflection** [comment]
@MikeVaz I think @sbadya is using hyperHTML and the question should be posted probably there, because with hyperHTML he can do that, but just trying would've shown already he could've done it.

hyperHTML is a DOM facade, not an innerHTML like operation, so it is possible to put a node in a template literal and it will be appended there (but not cloned).

However, you don't need to mix up the two syntaxes, you can just html`<my-component />` and it works.

**Comment by sbadya** [comment]
It works nice, but in dom there is a string <!--- hyper -some-number. What is it?
