### ISSUE TITLE
What is the current CDN version ?

### ISSUE THREAD

**Issue by noopole** [WebReflection/document-register-element#34]
Hi, I'm trying to run the js-perf benchmark on element creation.
http://jsperf.com/new-vs-create-element/3

Where can I find the current number or url for the current version (is it still 0.4.3)?
Thank you by advance.

**Comment by WebReflection** [comment]
`0.4.5` the version pushed to cdnJS is reflected in the package.json/tag of the repository. I will update the README though.

Here the full link:
http://cdnjs.cloudflare.com/ajax/libs/document-register-element/0.4.5/document-register-element.js

I am  not expecting any difference in terms of performance since that part of the code got probably untouched.

Best Regards

**Comment by noopole** [comment]
Thank you for your quick answer. I updated the test (no performance change, as you stated).
