### ISSUE TITLE
document.defineCustomElement in WebKit

### ISSUE THREAD

**Issue by simevidas** [WebReflection/document-register-element#41]
Just a quick heads up: WebKit is implementing an alternative custom element API:

https://twitter.com/ryosukeniwa/status/655640652827377664

**Comment by WebReflection** [comment]
I dont' have the label "heads up" but thanks a lot!

I'll keep it open until they answer my questions and see if I can work to improve portability.

**Comment by WebReflection** [comment]
it looks like the future support is worse than current one:
https://bugs.webkit.org/show_bug.cgi?id=150225#c4

In order to use native components I should filter only defined elements that inherits from HTMLElement, keeping the `is` attribute behavior intact as it is now.

At the end of the day this current polyfill should still work regardless, and I'm happy they used a different name so there won't be conflicts with this one.

**Comment by simevidas** [comment]
Keep in mind that this is a prototype. WebKit probably just wants to make something concrete that they can present at the [next meeting in December](http://www.w3.org/2015/10/26-webapps-minutes.html#item06). The [latest WebKit blog post](https://www.webkit.org/blog/4096/introducing-shadow-dom-api/) also suggest this:

> “Unfortunately, there are a few conflicting proposals on when and how to create a custom element. To help steer the discussion in W3C, we’re planning to prototype it in WebKit.”

**Comment by jasonmorganson** [comment]
The resolution at the latest meeting is to name this `defineElement`. 

See https://www.w3.org/2016/01/25-webapps-minutes.html#resolution06

**Comment by WebReflection** [comment]
AFAIK this is kinda moving on here:
https://github.com/WebReflection/document-register-element/issues/58
