### ISSUE TITLE
CDNJS

### ISSUE THREAD

**Issue by isaacewing** [WebReflection/document-register-element#51]
can you add a dre.min.js to the cdn instead of just the normal unformatted minified version when updating the CDNJS repo

**Comment by WebReflection** [comment]
sorry ... what?

**Comment by isaacewing** [comment]
for example, when i include the CDNJS repo like below
```javascript
<script src="//cdnjs.cloudflare.com/ajax/libs/document-register-element/0.5.3/document-register-element.js"
></script>
```

Could you also add a version that has the minified version of the JS file like
document-register-element.**min**.js"

**Comment by WebReflection** [comment]
the purpose of minification is to reduce the overall amount of bytes, right?
Why would you want 4 extra bytes per each minified URL? That would be eventually a no-brainer for a `.max` version, who cares if the name contains those extra 4 bytes.

Accordingly, you might find that [document-register-element.js](http://cdnjs.cloudflare.com/ajax/libs/document-register-element/0.5.3/document-register-element.js) **is the minified version** while to have the one that doesn't care about minification  you can use [document-register-element.max.js](http://cdnjs.cloudflare.com/ajax/libs/document-register-element/0.5.3/document-register-element.max.js)

As summary, there is a build process with a toolchain that makes files generation a straight forward and simple one shot procedure. If the purpose of minifing is reduce as much as possible a file size, I find it illogical to have all minified files containing those pointless extra 4 bytes so welcome to my world where the unminified version  is explicitly called `.max.js` and the production one doesn't need any reminder in  its own name and doesn't surely need to be bigger: it's minified for a reason!

... .right? 

Best Regards

**Comment by isaacewing** [comment]
I suppose that's a good point and I know the file is already minified, adding the .min. to the file name just maps well with all the other libraries in the CDN as they all have the *.min.js to the file so when I write a JS script that does a batch download for dependency injection, instead of looping through an array of files to download, I have to have a one-off hook that tests specifically for your file since there is no .min version. That's why I was requesting that.

**Comment by WebReflection** [comment]
> when I write a JS script that does a batch download for dependency injection

If I understand correctly, that means you are not using the CDN for what it's being created for and you most likely need a hook to this repository and update whatever download only once and only when a new release is available.

You can grab it directly from [here](https://raw.githubusercontent.com/WebReflection/document-register-element/master/build/document-register-element.js) or you can simply use `npm` like [Google AMP](https://github.com/ampproject/amphtml/blob/master/package.json#L21-L23) is doing already.

The fact everyone else is doing it wrong doesn't usually mean who actually thought about it should do it wrong as well so I am afraid all my projects are like this and I'm here to tell everyone else they can improve instead of generating automatically dumbly named files.

Apologies for any inconvenient, but I am sure you've got my point so thanks in  advance for your understanding.

**Comment by WebReflection** [comment]
the TL;DR version of this problem is: nobody needs non-minified version in production if not during debugging. That shouild be the naming exception, not the default one with a pointless `.min` in it.
