### ISSUE TITLE
Patched createdElement breaks instanceof.

### ISSUE THREAD

**Issue by Florian-R** [WebReflection/document-register-element#64]
Noticed this one when upgrading from 0.5.4 to 1.0.1.

See this [super dummy test case](http://requirebin.com/?gist=354fb2f5b3bc58fe9e7c1b0494434136).
Unfortunately, this breaks some third-party code which rely on `instanceof HTMLElement` checks.

Currently digging into the recent changes to know if this is fixable in some way and hopefully send a PR.

Thanks for your input.

**Comment by WebReflection** [comment]
you got me there, I've never thought somebody would've used `node instanceof HTMLElement` to distinguish between nodes, instead of `node.nodeName` which for non custom elements makes much more sense.

However, no excuses, my poly breaks these expectations and it shouldn't.
I'm thinking about a solution, because patching `document.createElement` is not enough: any native element could be grabbed at any time ... this is a tough one.

**Comment by WebReflection** [comment]
actually, would you mind trying `1.0.2` and tell me if it fixes the issue?

**Comment by WebReflection** [comment]
actually I have a test in place that shows it's fixed now. Thanks

**Comment by Florian-R** [comment]
Wow, that was quick, you were faster to fix it than me to locate the bug :+1:.  I can confirm the fix is OK with 1.0.4. 

Me just being curious, any reason you've used `Object.defineProperty` in the first time? 

Thanks a lot.

**Comment by WebReflection** [comment]
Because inheriting gives me full privileges to my prototype while natives are extremely differently handled by various vendors. WebKit has it frozen, others have some property non configurable but writable, etc. Indeed, with latest I'm working on right now, Safari can't possible have the `constructor` overwrite but at least `instanceof` works as expected.

**Comment by Florian-R** [comment]
I see. Thanks for the heads up.
