### ISSUE TITLE
installing document-register-element to friendly iframe

### ISSUE THREAD

**Issue by erwinmombay** [WebReflection/document-register-element#74]
so we would like to be able to install the document-register-element polyfill in a friendly iframe.

```js
const iframe = self.document.createElement('iframe');
self.installDocumentRegisterElement(/* window */ iframe.contentWindow,
    /* document */ iframe.contentWindowDocument);
iframe.srcdoc = '<amp-img></amp-img>';
```

so that the document-register-element code polyfill's custom-element on the friendly iframe.

```js
self.installDocumentRegisterElement = function(window, document) {
  // src/document-register-element.js body here
};
```

would it be reasonable to add a new template where we wrap src/document-register-element.js with this install function? If this sounds reasonable I can submit my PR

/cc @dvoytenko for further explanation

**Comment by WebReflection** [comment]
Any API method that is not spec'd won't probably land in this repo so I prefer to better understand your requirements and work out the possible best implementation.

If I understand correctly, you need a cross frame *aware* implementation of the `ComponentRegistry` so that not only the frame should have the ability to define and create custom elements, you also want to use your CE defined in the top window, e.g. `amp-img`, within that frame and without needing to redefine it there.

If that is correct, I might try to use a globally shared repository (via `top` instead of `window`) but you'll probably still need to include the polyfill as external script within each frame.

Are my conclusions correct? Does my solution sound reasonable?

**Comment by dvoytenko** [comment]
@erwinmombay @WebReflection thanks a lot for the comments!

What we need is simply to be able to install a polyfill in a friendly iframe, to make sure the case is equivalent to native CE.

One way I see we could approach this, we currently take advantage of `document-register-element.js` binary that's wrapper like this:
```
(function(window, document, Object, REGISTER_ELEMENT){'use strict';
...
}(window, document, Object, 'registerElement'));
```

If instead, we could create a module that looks like this:
```
export function installRegisterElement(window, document, Object, REGISTER_ELEMENT){
...
}
```

Then we should be able to simply run in on a friendly iframe:
```
installRegisterElement(
    iframe.contentWindow, 
    iframe.contentDocument, 
    iframe.contentWindow.Object, 
    'registerElement');
```

WDYT?

**Comment by WebReflection** [comment]
does the `export` bit need to be there? this module uses ES3 to ES5 compatible syntax, that would kinda stop any other person that would like to do the same without Babel upfront.

**Comment by erwinmombay** [comment]
oh definitely not, we'd want to do it the way where it fits in with document-register-element's conventions and platform targets. (i'd be ok with explicit global for example)

**Comment by WebReflection** [comment]
would something like this work?
https://github.com/WebReflection/document-register-element/blob/installable-custom-elements/build/install-custom-elements.max.js

it's called `installCustomElements` and you can put an `export` or a `module.exports = ` in front of the file if you want.

It doesn't need to be invoked with such silly signature so that `installCustomElements(window, document, Object)` would be enough, and I also have doubts about `document` and `Object` since I can easily grab them from the `window` (or maybe keep the document explicit and take the only Object from it)

The file won't probably land as update because I don't want to make this poly more obtrusive than it is already, polluting the global window with a function so I'd like to know how you're planning to consume this new version of the file that has a build a part like it is for the AMD version.

Thoughts ?

**Comment by WebReflection** [comment]
Alternatively, I could add a sneaky installer within the document, like a `__poly = {}` property that if present you could use to `document.__poly.installCustomElements(window, document)`. I don't know, I actually like the idea to be able to install it around, I don't want to cross the boundaries of the good polyfiller though

**Comment by erwinmombay** [comment]
consuming it as commonjs would probably be the easiest way for us. will double check again if that is the case

**Comment by dvoytenko** [comment]
Function in https://github.com/WebReflection/document-register-element/blob/installable-custom-elements/build/install-custom-elements.max.js is exactly what I'd like. If we don't like the signature, we can always do something like this:

```
function installCustomElements(window){'use strict';
var document = window.document, Object = window.Object;
```

Right?

**Comment by WebReflection** [comment]
My memories about how you retrieve the document from an iframe window tell
me that's not quite it, but I might try to figure it out at runtime so,
it's also my best pick.

**Comment by dvoytenko** [comment]
Alright. Let's do it! Should we send you a PR?

**Comment by WebReflection** [comment]
no need for it, I'll instrument the current `npm` package *only* to export such functionality. Would that work?

**Comment by dvoytenko** [comment]
@erwinmombay Would this work?

**Comment by erwinmombay** [comment]
@dvoytenko yep, should be good.

@WebReflection we really appreciate the help you've given!

**Comment by WebReflection** [comment]
I'll try to do some test and publish the new module by tomorrow evening. I hope that's OK

**Comment by dvoytenko** [comment]
@WebReflection That's perfect! Thanks a lot!

**Comment by WebReflection** [comment]
I forgot to push yesterday so `1.1.0` exports the module as a function.

```js
// by default requiring the module still pollute the global window
var installCustomElements = require('document-register-element');

// whenever you need to install it
installCustomElements(iframeWindow);
```

I hope this is compatible with your toolchain but if it's not please let me know.

**Comment by WebReflection** [comment]
> I forgot to push yesterday

meaning .. it's on `npm` right now

**Comment by dvoytenko** [comment]
@WebReflection Thanks a lot! It sounds like it'd work great.

**Comment by WebReflection** [comment]
please let me know if it does.

Next up: should defined CE on top be reflected on other frames? Right now there's no logic involved at all so `adoptedChildCallback` won't ever trigger (it's not even there) and defined element on `top` won't be available in frames.

I need to test how it is on Canary while you should tell me if, as it is, this poly is already OK for your case.

I'll close this in the meanwhile since it's somehow solved in latest version.

**Comment by dvoytenko** [comment]
@WebReflection Thanks! I think we don't need to reflect CEs in other frames since it's somewhat ambiguous operation. But I'll run through the adopt steps and see if they are applicable.
