### ISSUE TITLE
Complete example available anywhere?

### ISSUE THREAD

**Issue by DaneGrinder** [WebReflection/document-register-element#78]
As the headline says, I just can't get a complete example to work with "import", "template" and "custom element".

I'm using this to polyfill the customElement.define(), and "webcomponentsjs" to polyfill the rest, but I just can't get it to work. I only really need it to work in "Electron" (aka. Chrome).

Any chance you could supply a complete working example? :-)

Henrik

**Comment by WebReflection** [comment]
If you are using `webcomponents.js` you don't need this polyfill, specially if the target is Electron (aka. Chrome ... have you tried [benja](http://benja.io/) ? it's awesome!)

Just as reminder, `webcomponents.js` js targeting mostly Chrome since it's from Google for Googlers so please ask them how to have a CustomElements V1 in there instead of asking me how to make the whole WebComponents specifuication/group work with this poly which is specifically designed for Custom Elements only, and nothing else.

**Comment by DaneGrinder** [comment]
Benja looks way cool :-) Defiantly going to look into that

webcomponents.js (google) does not have a working v1 implementation yet, and they don't seem to have a clear roadmap for making one. Yours is the only one I've found, but as you say, it's specifically customElements.define(), so I'm stuck because I can't get "template" to work with it.

Thank you for taking your time to answer me. I'll figure something out :-)

**Comment by WebReflection** [comment]
> webcomponents.js (google) does not have a working v1 implementation yet

maybe you are not looking at the proper branch?
https://github.com/WebComponents/webcomponentsjs/tree/v1

**Comment by treshugart** [comment]
@DaneGrinder, may I ask why you're using polyfills if you only need to target Electron?
